version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "lightning"
        versions:
          - "2.5.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
