steps:
  - name: "alpine"
    id: "Replace values in the training config"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache gettext
        envsubst < vertex-config.yaml > vertex-config.yaml.tmp
        mv vertex-config.yaml.tmp vertex-config.yaml
    secretEnv: ["WANDB_API_KEY"]

  - name: "alpine"
    id: "Show config"
    waitFor: ["Replace values in the training config"]
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat vertex-config.yaml

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Train container image"
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-train-build",
        "-f",
        "dockerfiles/train.dockerfile"
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Train container image"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-train-build"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Trigger Vertex AI Custom Job"
    args:
      [
        "gcloud",
        "ai",
        "custom-jobs",
        "create",
        "--region=europe-west1",
        "--display-name=test-run",
        "--config=vertex-config.yaml"
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Train on vertex AI"
    waitFor: ["Replace values in the training config"]
    args:
      [
        "ai",
        "custom-jobs",
        "create",
        "--region",
        "europe-west1",
        "--display-name",
        "example-mlops-job",
        "--config",
        "${_VERTEX_TRAIN_CONFIG}"
      ]

substitutions:
  _VERTEX_TRAIN_CONFIG: "vertex-config.yaml"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
      env: "WANDB_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY
