steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build API container image"
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-api-build",
        "-f",
        "dockerfiles/api.dockerfile"
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push API container image"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-api-build"
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend container image"
    args:
      [
        "build",
        ".",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-frontend-build",
        "-f",
        "dockerfiles/frontend.dockerfile"
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Frontend container image"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/course02476/02476-frontend-build"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
