workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
    replicaCount: 1
    containerSpec:
      imageUri: "gcr.io/sage-dragon-448009-f7/1610853383c09"
      # args:
      #   - "--train"
      #   - "--epochs=10"
