workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
    replicaCount: 1
    containerSpec:
      imageUri: "europe-west1-docker.pkg.dev/sage-dragon-448009-f7/course02476/02476-train-build:latest"
      env:
        - name: GCS_BUCKET_NAME
          value: "02476-data"
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_ENTITY
          value: $WANDB_ENTITY
        - name: WANDB_PROJECT
          value: $WANDB_PROJECT
        - name: WANDB_MODEL_NAME
          value: $WANDB_MODEL_NAME
        - name: WANDB_REGISTRY
          value: $WANDB_REGISTRY
