_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
                - 106
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: Mushroom classification
epochs:
    value: 5
learning_rate:
    value: 0.001
