data:
  data_path: data/raw_subset
  batch_size: 32
  num_workers: 16
  # Percentage of the full dataset to use, which is then further
  # split into train, test, and validation sets
  percent_of_data: 1
  # The following 3 values must sum to 1
  train_pct: 0.8
  test_pct: 0.1
  val_pct: 0.1

trainer:
  max_epochs: 5
  learning_rate: 0.001

model:
  file_name: mushroom_model

# This seed will be used for all RNGs in the code
# In theory! Additional setup may be needed
seed: 42
